#!/usr/bin/env bash

set -euo pipefail

clj-kondo  --lint src test --cache false

lein cljfmt check src test examples

# Ancient
# NOTE: temporarily disabled until active development period
# mkdir -p target
# lein ancient
#
# mkdir -p target
# lein ancient :plugins
